[request_definition]
r = sub, obj, act, extra

[policy_definition]
p = sub, obj, act, role_or_condition

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act && eval(p.role_or_condition)
